baseurl = "https://marcus-stockholm.github.io/" # Make sure to end baseurl with a '/'
title = "Game programmer"
author = "Marcus Jungell"
# Shown in the side menu
canonifyurls = true
paginate = 10
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Engineering mathematics"
  # brand = ""
  googleAnalytics = ""
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = ""
    pre = "<img src='/icons/home.svg' width='16' height='16' />"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Blog"
    pre = "<img src='/icons/brackets.svg' width='16' height='16' />"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Services"
    pre = "<img src='/icons/code.svg' width='16' height='16' />"
    weight = 3
    identifier = "services"
    url = "/services/"
  [[menu.main]]
    name = "Profile"
    pre = "<img src='/icons/profile.svg' width='16' height='16' />"
    weight = 4
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Legal"
    pre = "<img src='/icons/law.svg' width='16' height='16' />"
    weight = 5
    identifier = "legal"
    url = "/legal/"
  [[menu.main]]
    name = "Contact"
    pre = "<img src='/icons/envelope.svg' width='16' height='16' />"
    weight = 6
    identifier = "contact"
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  github = "marcus-stockholm"